title: 무과장의 개발로 개발
description: '개발로 개발하는 개발자 무과장 블로그입니다. :)'
author: 무과장
github: https://github.com/jmkim0213
about: 무과장의 개발로 개발
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-github
      link: "https://github.com/jmkim0213"
    - icon: fa-facebook
      link: "https://www.facebook.com/yskim6217"
    - icon: fa-instagram
      link: "https://www.instagram.com/jmkim0213/"

urls:
    - text: About Me
      url: /about/
    # - text: My Projects
    #   url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://jmkim0213.github.io"
baseurl: ""
paginate: 20
per_page: 10
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
